import './globals.css'
import { Ubuntu } from 'next/font/google'
import Navbar from './components/Navbar'
const font = Ubuntu({ weight: ["300", "400", "500", "700"], subsets:['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        {children}
        </body>
    </html>
  )
}
