import './globals.css'
import { Inter } from 'next/font/google'
import logoblue from './logoblue.ico'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CodeAbhi',
  description: 'Generated by create next app',

}

export default function RootLayout({ children }) {
  return (

    <html lang="en">
          <head>
{/* <link rel='icon' href={logoblue}/> */}


    </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
